// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBook = "book"

// Book mapped from table <book>
type Book struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Author      string    `gorm:"column:author;not null" json:"author"`
	Price       int32     `gorm:"column:price;not null" json:"price"`
	PublishDate time.Time `gorm:"column:publish_date" json:"publish_date"`
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
